// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Task.proto

package ale.rains.demo.proto;

public final class TaskProto {
  private TaskProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * 枚举
   * </pre>
   *
   * Protobuf enum {@code proto.Action}
   */
  public enum Action
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>START = 0;</code>
     */
    START(0),
    /**
     * <code>PAUSE = 1;</code>
     */
    PAUSE(1),
    /**
     * <code>RESUME = 2;</code>
     */
    RESUME(2),
    /**
     * <code>STOP = 3;</code>
     */
    STOP(3),
    ;

    /**
     * <code>START = 0;</code>
     */
    public static final int START_VALUE = 0;
    /**
     * <code>PAUSE = 1;</code>
     */
    public static final int PAUSE_VALUE = 1;
    /**
     * <code>RESUME = 2;</code>
     */
    public static final int RESUME_VALUE = 2;
    /**
     * <code>STOP = 3;</code>
     */
    public static final int STOP_VALUE = 3;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Action valueOf(int value) {
      return forNumber(value);
    }

    public static Action forNumber(int value) {
      switch (value) {
        case 0: return START;
        case 1: return PAUSE;
        case 2: return RESUME;
        case 3: return STOP;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Action>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Action> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Action>() {
            public Action findValueByNumber(int number) {
              return Action.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ale.rains.demo.proto.TaskProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final Action[] VALUES = values();

    public static Action valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Action(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.Action)
  }

  /**
   * Protobuf enum {@code proto.Result}
   */
  public enum Result
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SUCCESS = 0;</code>
     */
    SUCCESS(0),
    /**
     * <code>FAILED = 1;</code>
     */
    FAILED(1),
    ;

    /**
     * <code>SUCCESS = 0;</code>
     */
    public static final int SUCCESS_VALUE = 0;
    /**
     * <code>FAILED = 1;</code>
     */
    public static final int FAILED_VALUE = 1;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Result valueOf(int value) {
      return forNumber(value);
    }

    public static Result forNumber(int value) {
      switch (value) {
        case 0: return SUCCESS;
        case 1: return FAILED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Result>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Result> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Result>() {
            public Result findValueByNumber(int number) {
              return Result.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ale.rains.demo.proto.TaskProto.getDescriptor().getEnumTypes().get(1);
    }

    private static final Result[] VALUES = values();

    public static Result valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Result(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.Result)
  }

  public interface TaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.Task)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string taskId = 1;</code>
     */
    boolean hasTaskId();
    /**
     * <code>required string taskId = 1;</code>
     */
    java.lang.String getTaskId();
    /**
     * <code>required string taskId = 1;</code>
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <code>required .proto.Action action = 2;</code>
     */
    boolean hasAction();
    /**
     * <code>required .proto.Action action = 2;</code>
     */
    ale.rains.demo.proto.TaskProto.Action getAction();

    /**
     * <code>required .proto.Result result = 3;</code>
     */
    boolean hasResult();
    /**
     * <code>required .proto.Result result = 3;</code>
     */
    ale.rains.demo.proto.TaskProto.Result getResult();
  }
  /**
   * <pre>
   * Message对象名，一般任务Message和Java中的Class关键字类似
   * </pre>
   *
   * Protobuf type {@code proto.Task}
   */
  public  static final class Task extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.Task)
      TaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Task.newBuilder() to construct.
    private Task(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Task() {
      taskId_ = "";
      action_ = 0;
      result_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Task(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              taskId_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              ale.rains.demo.proto.TaskProto.Action value = ale.rains.demo.proto.TaskProto.Action.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                action_ = rawValue;
              }
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              ale.rains.demo.proto.TaskProto.Result value = ale.rains.demo.proto.TaskProto.Result.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                result_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ale.rains.demo.proto.TaskProto.internal_static_proto_Task_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ale.rains.demo.proto.TaskProto.internal_static_proto_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ale.rains.demo.proto.TaskProto.Task.class, ale.rains.demo.proto.TaskProto.Task.Builder.class);
    }

    private int bitField0_;
    public static final int TASKID_FIELD_NUMBER = 1;
    private volatile java.lang.Object taskId_;
    /**
     * <code>required string taskId = 1;</code>
     */
    public boolean hasTaskId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string taskId = 1;</code>
     */
    public java.lang.String getTaskId() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          taskId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string taskId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      java.lang.Object ref = taskId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ACTION_FIELD_NUMBER = 2;
    private int action_;
    /**
     * <code>required .proto.Action action = 2;</code>
     */
    public boolean hasAction() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required .proto.Action action = 2;</code>
     */
    public ale.rains.demo.proto.TaskProto.Action getAction() {
      @SuppressWarnings("deprecation")
      ale.rains.demo.proto.TaskProto.Action result = ale.rains.demo.proto.TaskProto.Action.valueOf(action_);
      return result == null ? ale.rains.demo.proto.TaskProto.Action.START : result;
    }

    public static final int RESULT_FIELD_NUMBER = 3;
    private int result_;
    /**
     * <code>required .proto.Result result = 3;</code>
     */
    public boolean hasResult() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required .proto.Result result = 3;</code>
     */
    public ale.rains.demo.proto.TaskProto.Result getResult() {
      @SuppressWarnings("deprecation")
      ale.rains.demo.proto.TaskProto.Result result = ale.rains.demo.proto.TaskProto.Result.valueOf(result_);
      return result == null ? ale.rains.demo.proto.TaskProto.Result.SUCCESS : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasTaskId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasAction()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasResult()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeEnum(2, action_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeEnum(3, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, action_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ale.rains.demo.proto.TaskProto.Task)) {
        return super.equals(obj);
      }
      ale.rains.demo.proto.TaskProto.Task other = (ale.rains.demo.proto.TaskProto.Task) obj;

      if (hasTaskId() != other.hasTaskId()) return false;
      if (hasTaskId()) {
        if (!getTaskId()
            .equals(other.getTaskId())) return false;
      }
      if (hasAction() != other.hasAction()) return false;
      if (hasAction()) {
        if (action_ != other.action_) return false;
      }
      if (hasResult() != other.hasResult()) return false;
      if (hasResult()) {
        if (result_ != other.result_) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasTaskId()) {
        hash = (37 * hash) + TASKID_FIELD_NUMBER;
        hash = (53 * hash) + getTaskId().hashCode();
      }
      if (hasAction()) {
        hash = (37 * hash) + ACTION_FIELD_NUMBER;
        hash = (53 * hash) + action_;
      }
      if (hasResult()) {
        hash = (37 * hash) + RESULT_FIELD_NUMBER;
        hash = (53 * hash) + result_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ale.rains.demo.proto.TaskProto.Task parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ale.rains.demo.proto.TaskProto.Task parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ale.rains.demo.proto.TaskProto.Task parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ale.rains.demo.proto.TaskProto.Task parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ale.rains.demo.proto.TaskProto.Task parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ale.rains.demo.proto.TaskProto.Task parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ale.rains.demo.proto.TaskProto.Task parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ale.rains.demo.proto.TaskProto.Task parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ale.rains.demo.proto.TaskProto.Task parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ale.rains.demo.proto.TaskProto.Task parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ale.rains.demo.proto.TaskProto.Task parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ale.rains.demo.proto.TaskProto.Task parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ale.rains.demo.proto.TaskProto.Task prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Message对象名，一般任务Message和Java中的Class关键字类似
     * </pre>
     *
     * Protobuf type {@code proto.Task}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.Task)
        ale.rains.demo.proto.TaskProto.TaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ale.rains.demo.proto.TaskProto.internal_static_proto_Task_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ale.rains.demo.proto.TaskProto.internal_static_proto_Task_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ale.rains.demo.proto.TaskProto.Task.class, ale.rains.demo.proto.TaskProto.Task.Builder.class);
      }

      // Construct using ale.rains.demo.proto.TaskProto.Task.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        taskId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        action_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        result_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ale.rains.demo.proto.TaskProto.internal_static_proto_Task_descriptor;
      }

      @java.lang.Override
      public ale.rains.demo.proto.TaskProto.Task getDefaultInstanceForType() {
        return ale.rains.demo.proto.TaskProto.Task.getDefaultInstance();
      }

      @java.lang.Override
      public ale.rains.demo.proto.TaskProto.Task build() {
        ale.rains.demo.proto.TaskProto.Task result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public ale.rains.demo.proto.TaskProto.Task buildPartial() {
        ale.rains.demo.proto.TaskProto.Task result = new ale.rains.demo.proto.TaskProto.Task(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.taskId_ = taskId_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.action_ = action_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.result_ = result_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ale.rains.demo.proto.TaskProto.Task) {
          return mergeFrom((ale.rains.demo.proto.TaskProto.Task)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ale.rains.demo.proto.TaskProto.Task other) {
        if (other == ale.rains.demo.proto.TaskProto.Task.getDefaultInstance()) return this;
        if (other.hasTaskId()) {
          bitField0_ |= 0x00000001;
          taskId_ = other.taskId_;
          onChanged();
        }
        if (other.hasAction()) {
          setAction(other.getAction());
        }
        if (other.hasResult()) {
          setResult(other.getResult());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasTaskId()) {
          return false;
        }
        if (!hasAction()) {
          return false;
        }
        if (!hasResult()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ale.rains.demo.proto.TaskProto.Task parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ale.rains.demo.proto.TaskProto.Task) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object taskId_ = "";
      /**
       * <code>required string taskId = 1;</code>
       */
      public boolean hasTaskId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string taskId = 1;</code>
       */
      public java.lang.String getTaskId() {
        java.lang.Object ref = taskId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            taskId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string taskId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        java.lang.Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string taskId = 1;</code>
       */
      public Builder setTaskId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string taskId = 1;</code>
       */
      public Builder clearTaskId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>required string taskId = 1;</code>
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        taskId_ = value;
        onChanged();
        return this;
      }

      private int action_ = 0;
      /**
       * <code>required .proto.Action action = 2;</code>
       */
      public boolean hasAction() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required .proto.Action action = 2;</code>
       */
      public ale.rains.demo.proto.TaskProto.Action getAction() {
        @SuppressWarnings("deprecation")
        ale.rains.demo.proto.TaskProto.Action result = ale.rains.demo.proto.TaskProto.Action.valueOf(action_);
        return result == null ? ale.rains.demo.proto.TaskProto.Action.START : result;
      }
      /**
       * <code>required .proto.Action action = 2;</code>
       */
      public Builder setAction(ale.rains.demo.proto.TaskProto.Action value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        action_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.Action action = 2;</code>
       */
      public Builder clearAction() {
        bitField0_ = (bitField0_ & ~0x00000002);
        action_ = 0;
        onChanged();
        return this;
      }

      private int result_ = 0;
      /**
       * <code>required .proto.Result result = 3;</code>
       */
      public boolean hasResult() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required .proto.Result result = 3;</code>
       */
      public ale.rains.demo.proto.TaskProto.Result getResult() {
        @SuppressWarnings("deprecation")
        ale.rains.demo.proto.TaskProto.Result result = ale.rains.demo.proto.TaskProto.Result.valueOf(result_);
        return result == null ? ale.rains.demo.proto.TaskProto.Result.SUCCESS : result;
      }
      /**
       * <code>required .proto.Result result = 3;</code>
       */
      public Builder setResult(ale.rains.demo.proto.TaskProto.Result value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        result_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .proto.Result result = 3;</code>
       */
      public Builder clearResult() {
        bitField0_ = (bitField0_ & ~0x00000004);
        result_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.Task)
    }

    // @@protoc_insertion_point(class_scope:proto.Task)
    private static final ale.rains.demo.proto.TaskProto.Task DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ale.rains.demo.proto.TaskProto.Task();
    }

    public static ale.rains.demo.proto.TaskProto.Task getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<Task>
        PARSER = new com.google.protobuf.AbstractParser<Task>() {
      @java.lang.Override
      public Task parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Task(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Task> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Task> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public ale.rains.demo.proto.TaskProto.Task getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Task_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Task_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nTask.proto\022\005proto\"T\n\004Task\022\016\n\006taskId\030\001 " +
      "\002(\t\022\035\n\006action\030\002 \002(\0162\r.proto.Action\022\035\n\006re" +
      "sult\030\003 \002(\0162\r.proto.Result*4\n\006Action\022\t\n\005S" +
      "TART\020\000\022\t\n\005PAUSE\020\001\022\n\n\006RESUME\020\002\022\010\n\004STOP\020\003*" +
      "!\n\006Result\022\013\n\007SUCCESS\020\000\022\n\n\006FAILED\020\001B!\n\024al" +
      "e.rains.demo.protoB\tTaskProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_Task_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Task_descriptor,
        new java.lang.String[] { "TaskId", "Action", "Result", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
