/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ale_rains_xxhash_XXHashJNI */

#ifndef _Included_ale_rains_xxhash_XXHashJNI
#define _Included_ale_rains_xxhash_XXHashJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ale_rains_xxhash_XXHashJNI_init
  (JNIEnv *, jclass);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH32
 * Signature: ([BIII)I
 */
JNIEXPORT jint JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH32
  (JNIEnv *, jclass, jbyteArray, jint, jint, jint);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH32BB
 * Signature: (Ljava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH32BB
  (JNIEnv *, jclass, jobject, jint, jint, jint);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH32_init
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH32_1init
  (JNIEnv *, jclass, jint);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH32_update
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH32_1update
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH32_digest
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH32_1digest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH32_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH32_1free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH64
 * Signature: ([BIIJ)J
 */
JNIEXPORT jlong JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH64
  (JNIEnv *, jclass, jbyteArray, jint, jint, jlong);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH64BB
 * Signature: (Ljava/nio/ByteBuffer;IIJ)J
 */
JNIEXPORT jlong JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH64BB
  (JNIEnv *, jclass, jobject, jint, jint, jlong);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH64_init
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH64_1init
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH64_update
 * Signature: (J[BII)V
 */
JNIEXPORT void JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH64_1update
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH64_digest
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH64_1digest
  (JNIEnv *, jclass, jlong);

/*
 * Class:     ale_rains_xxhash_XXHashJNI
 * Method:    XXH64_free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_ale_rains_xxhash_XXHashJNI_XXH64_1free
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
